import MainHeader from "@/components/layout/mainHeader";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <MainHeader />
        <div className="pt-16  md:mx-12 lg:mx-48">{children}</div>
      </body>
    </html>
  );
}
